### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by squadgazzz** [autolume/autolux#18]
Tried to install autolux with pip with no luck. Got same issue: https://github.com/autolume/autolux/issues/1
Then I tried to use pip2 and got this error:

$ autolux
DAEMON MODE: False
CROPPING: True
FADE TIME: 800
SLEEP TIME: 1200
DISPLAY RANGE: 5 100
LEARNING MODE: True
BRIGHTNESS RANGE: 5000 60000
RECALIBRATE EVERY: 60000
FOLLOW WINDOW PID: False
FOLLOW WINDOW TITLE: True
SCREENSHOT CMD import -silent -colorspace gray -screen -w root -quality 20 -crop 10x100%+400+0
LOADING LUMA MAP /root/.config/autolux/luma_map.p
WARNING: NOT LOADING LUMA MAP [Errno 2] No such file or directory: '/root/.config/autolux/luma_map.p'
[Errno 2] No such file or directory
[Errno 2] No such file or directory
[Errno 2] No such file or directory
[Errno 2] No such file or directory
.
.
.

**Comment by okayzed** [comment]
the first thing is that you shouldn't run it as root. the following is what i get when i run it as root, but it works correctly (the final few lines are examples of it changing brightness when i switch windows)


```
root@chalk:~/.config/autolux# autolux
DAEMON MODE: False
CROPPING: True
FADE TIME: 800
SLEEP TIME: 1200
DISPLAY RANGE: 5 100
LEARNING MODE: True
BRIGHTNESS RANGE: 5000 60000
RECALIBRATE EVERY: 60000
FOLLOW WINDOW PID: False
FOLLOW WINDOW TITLE: True
SCREENSHOT CMD import -silent -colorspace gray -screen -w root -quality 20 -crop 10x100%+400+0
LOADING LUMA MAP /root/.config/autolux/luma_map.p
WARNING: NOT LOADING LUMA MAP [Errno 2] No such file or directory: '/root/.config/autolux/luma_map.p'
MODEL|TS:1542897343, LUMA:00000, NEW GAMMA:1.00, NEW BRIGHTNESS: 100/100
MODEL|TS:1542897347, LUMA:55000, NEW GAMMA:0.00, NEW BRIGHTNESS: 5/100
MODEL|TS:1542897349, LUMA:00000, NEW GAMMA:1.00, NEW BRIGHTNESS: 100/100
MODEL|TS:1542897351, LUMA:55000, NEW GAMMA:0.00, NEW BRIGHTNESS: 5/100
MODEL|TS:1542897352, LUMA:00000, NEW GAMMA:1.00, NEW BRIGHTNESS: 100/100
```

i don't know what is going wrong in your setup, but one thing that comes to mind is: do you have `import` on your path? it is part of ImageMagick and is used for taking the screenshots to determine the average brightness of the on-screen contents

**Comment by squadgazzz** [comment]
> do you have import on your path?

How to check it properly?

**Comment by okayzed** [comment]
what distro are you on?

if you type `which import` it will tell you if the import binary is installed and in your path. if it isn't, you can install imagemagick through your package manager and get it. 

you can also type `import --help` - if it says "not found" or similar, then its not installed

**Comment by squadgazzz** [comment]
> what distro are you on?
> 
> if you type `which import` it will tell you if the import binary is installed and in your path. if it isn't, you can install imagemagick through your package manager and get it.
> 
> you can also type `import --help` - if it says "not found" or similar, then its not installed

yep, I have this package installed.

**Comment by okayzed** [comment]
the programs you need installed are:

* import
* xdotool
* xbacklight 


I uninstalled `xdotool` and was able to get the following output:

```
okay@chalk:~/tonka/src/autolux/autolux$ autolux
DAEMON MODE: False
CROPPING: True
FADE TIME: 800
SLEEP TIME: 1200
DISPLAY RANGE: 5 100
LEARNING MODE: True
BRIGHTNESS RANGE: 5000 60000
RECALIBRATE EVERY: 60000
FOLLOW WINDOW PID: False
FOLLOW WINDOW TITLE: True
SCREENSHOT CMD import -silent -colorspace gray -screen -w root -quality 20 -crop 10x100%+400+0
LOADED 1000 LUMA OBSERVATIONS
LOADING LUMA MAP /home/okay/.config/autolux/luma_map.p
TIME MAP IS 100% COMPLETE, LUMA MAP IS 111% COMPLETE
[Errno 2] No such file or directory
[Errno 2] No such file or directory
[Errno 2] No such file or directory
[Errno 2] No such file or directory
[Errno 2] No such file or directory
[Errno 2] No such file or directory
[Errno 2] No such file or directory
[Errno 2] No such file or directory
[Errno 2] No such file or directory
[Errno 2] No such file or directory
[Errno 2] No such file or directory
[Errno 2] No such file or directory
[Errno 2] No such file or directory
[Errno 2] No such file or directory



```

**Comment by okayzed** [comment]
if this solved the issue, i will close it out (in 24 hours)

please let me know if you have any feature requests or other bugs you run into

thanks!

**Comment by squadgazzz** [comment]
Now I have this error:

```
$ autolux
DAEMON MODE: False
CROPPING: True
FADE TIME: 800
SLEEP TIME: 1200
DISPLAY RANGE: 5 100
LEARNING MODE: True
BRIGHTNESS RANGE: 5000 60000
RECALIBRATE EVERY: 60000
FOLLOW WINDOW PID: False
FOLLOW WINDOW TITLE: True
SCREENSHOT CMD import -silent -colorspace gray -screen -w root -quality 20 -crop 10x100%+400+0
LOADING LUMA MAP /home/user/.config/autolux/luma_map.p
WARNING: NOT LOADING LUMA MAP [Errno 2] No such file or directory: '/home/user/.config/autolux/luma_map.p'
MODEL|TS:1543221221, LUMA:37000, NEW GAMMA:0.33, NEW BRIGHTNESS: 36/100
Traceback (most recent call last):
  File "/usr/bin/autolux", line 4, in <module>
    autolux.run()
  File "/usr/lib/python2.7/site-packages/autolux/autolux.py", line 196, in run
    monitor_luma()
  File "/usr/lib/python2.7/site-packages/autolux/autolux.py", line 114, in monitor_luma
    models.add_observation(prev_brightness, prev_mean)
  File "/usr/lib/python2.7/site-packages/autolux/models.py", line 168, in add_observation
    cur_bright = autolux.get_brightness()
  File "/usr/lib/python2.7/site-packages/autolux/autolux.py", line 30, in get_brightness
    return xbacklight.get_brightness()
  File "/usr/lib/python2.7/site-packages/autolux/xbacklight.py", line 55, in get_brightness
    ctrl = Controller(ctrls[0])
IndexError: list index out of range
```

**Comment by okayzed** [comment]
what happens when you the following two commands?

* `xbacklight -get`
* `ls /sys/class/backlight`

thanks!

**Comment by squadgazzz** [comment]
> what happens when you the following two commands?
> 
> * `xbacklight -get`
> * `ls /sys/class/backlight`
> 
> thanks!

nothing.

```
$ xbacklight -get
$ ls /sys/class/backlight
$ 
```

**Comment by okayzed** [comment]
thanks for the patience and i'm sorry its been difficult to get autolux working. it seems xbacklight is broken on your system. i don't know the details of your environment, but have been looking into various solutions.

if you do a search for `<my distro> xbacklight broken` it might yield some results that will help fix it. often, it seems the break is due to either intel drivers or nvidia drivers or a permissions issue. 

other than that, i've come across this program: https://github.com/haikarainen/light which says it has less bugs than xbacklight. if `light` is in your distro's repositories and works for you, i can modify autolux to work with the `light` program.

**Comment by JLTastet** [comment]
I have the same issue on Fedora 29 (Gnome / Wayland).
```
~> xbacklight -get
No outputs have backlight property
~> ls /sys/class/backlight
intel_backlight@
```

**Comment by okayzed** [comment]
@JLTastet thanks for trying out autolux!

https://askubuntu.com/questions/790972/xbacklight-no-outputs-have-backlight-property/902934 and https://askubuntu.com/questions/715306/xbacklight-no-outputs-have-backlight-property-no-sys-class-backlight-folder look relevant.

It seems like you might need a setting in your xorg.conf (if you are on a laptop with a backlight). the same search ("<my distro> xbacklight intel_backlight broken) or similar might  also yield good results.

**Comment by JLTastet** [comment]
I just tried `autolux` on Xorg, and now I get a slightly different result:
```
~> autolux
DAEMON MODE: False
CROPPING: True
FADE TIME: 800
SLEEP TIME: 1200
DISPLAY RANGE: 5 100
LEARNING MODE: True
BRIGHTNESS RANGE: 5000 60000
RECALIBRATE EVERY: 60000
FOLLOW WINDOW PID: False
FOLLOW WINDOW TITLE: True
SCREENSHOT CMD import -silent -colorspace gray -screen -w root -quality 20 -crop 10x100%+400+0
LOADED 1 LUMA OBSERVATIONS
LOADING LUMA MAP /home/jl/.config/autolux/luma_map.p
TIME MAP IS 24% COMPLETE, LUMA MAP IS 5% COMPLETE
MODEL|TS:1567348383, LUMA:28500, NEW GAMMA:0.48, NEW BRIGHTNESS: 51/100
INPUT|TS:1567348388, LUMA:28500, CUR:48.00, EXP:51.0
LEARN|TS:1567348388, LUMA:28500, HOUR: 16:30, PREV:None, NEW:48
MODEL|TS:1567348392, LUMA:47000, NEW GAMMA:0.15, NEW BRIGHTNESS: 19/100
INPUT|TS:1567348393, LUMA:47000, CUR:48.00, EXP:19.0
LEARN|TS:1567348393, LUMA:47000, HOUR: 16:30, PREV:None, NEW:48
MODEL|TS:1567348394, LUMA:28500, NEW GAMMA:0.48, NEW BRIGHTNESS: 48/100
MODEL|TS:1567348398, LUMA:20500, NEW GAMMA:0.63, NEW BRIGHTNESS: 65/100
INPUT|TS:1567348399, LUMA:20500, CUR:48.00, EXP:65.0
LEARN|TS:1567348399, LUMA:20500, HOUR: 16:30, PREV:None, NEW:48
MODEL|TS:1567348402, LUMA:07000, NEW GAMMA:0.87, NEW BRIGHTNESS: 88/100
INPUT|TS:1567348403, LUMA:07000, CUR:48.00, EXP:88.0
LEARN|TS:1567348403, LUMA:07000, HOUR: 16:30, PREV:None, NEW:48
MODEL|TS:1567348404, LUMA:29500, NEW GAMMA:0.46, NEW BRIGHTNESS: 49/100
MODEL|TS:1567348407, LUMA:07500, NEW GAMMA:0.86, NEW BRIGHTNESS: 87/100
INPUT|TS:1567348408, LUMA:07500, CUR:48.00, EXP:87.0
LEARN|TS:1567348408, LUMA:07500, HOUR: 16:30, PREV:None, NEW:48
MODEL|TS:1567348409, LUMA:30000, NEW GAMMA:0.45, NEW BRIGHTNESS: 48/100
MODEL|TS:1567348412, LUMA:08000, NEW GAMMA:0.85, NEW BRIGHTNESS: 86/100
INPUT|TS:1567348414, LUMA:08000, CUR:48.00, EXP:86.0
LEARN|TS:1567348414, LUMA:08000, HOUR: 16:30, PREV:None, NEW:48
MODEL|TS:1567348415, LUMA:30500, NEW GAMMA:0.45, NEW BRIGHTNESS: 47/100
```
It seems to compute the new brightness, but it is unable to set it, since `xbacklight` still does not work:
```
~> xbacklight -get
~> ls /sys/class/backlight
intel_backlight@
```
However, I have also tried `light`, and it works perfectly, both on Xorg and Wayland (!)

**Comment by okayzed** [comment]
Ok, we can modify autolux to use "light" command. Where is "light" from? I don't see it in my ubuntu repos.

Last year, I modified autolux to allow for setting with xrandr earlier, see https://github.com/autolume/autolux/blob/master/autolux/autolux.py#L15 and https://github.com/autolume/autolux/commit/b989fbf0c492bfa2e4ece5fd6fef5f12b1707d6d. Mostly it requires adding a new config option and then modifying set_brightness and get_brightness to call into "light" when that option is set. 


If you can add "light" as a supported program to the source, great, otherwise I will add support after installing it.

**Comment by JLTastet** [comment]
The repository is hosted on GitHub: https://github.com/haikarainen/light

On Fedora 29, there is a package called `light`. I could not find it for Ubuntu (maybe there is a PPA?), but the README contains instructions for manual installation or creating a `.deb`. In any case, we should probably keep `xbacklight` as a default.

I had a quick look at the code, and it seems that adding support for `light` should indeed be very straightforward. I can try to do it this week. Not sure it will be enough to get `autolux` working on Wayland, but let's try and see!

**Comment by okayzed** [comment]
Great! let me know if you have any questions. You should be able to run autolux with `python autolux/autolux.py` from the repo's root dir. 

I just read through the whole thread and saw that I suggested `light` program earlier, it's funny that I forgot about it. If it helps with wayland, that'll be really nice

**Comment by JLTastet** [comment]
PR opened: #20. Please destroy ;)

Under Wayland, I now get the following error when trying to run `autolux`:
```
import: unable to read X window image `root': Resource temporarily unavailable @ error/xwindow.c/XImportImage/4979.
import: missing an image filename `info:' @ error/import.c/ImportImageCommand/1289.
```
I will check what are our options for Wayland. There seem to be some compositor-specific APIs for at least Gnome and KDE, but the PipeWire framework looks promising too.

**Comment by okayzed** [comment]
awesome! that error looks related to the screenshot taking (`import -w root`) - I'm out now but will review more in a few hours. initially, code looks good to me.

**Comment by okayzed** [comment]
After some initial research, it looks like wayland does not allow applications to take screenshots of other applications for security reasons but various compositors and shells (weston and gnome-shell) reintroduce that feature. 

If your shell / compositor has an external API for taking screenshots, we can add an option for using it to autolux. (https://gitlab.freedesktop.org/wayland/wayland/issues/32)

**Comment by JLTastet** [comment]
Thanks! I'll have a look at the existing APIs. Gnome Shell has `gnome-screenshot`, but it is awfully slow and "flashes" the screen every time a screenshot is taken, which would be suboptimal :smile:

**Comment by okayzed** [comment]
for wayland: https://github.com/emersion/grim
